# "It took the night to believe"

language: c

before_script:
  - cmake $CMAKE_GENERATOR .
  
sudo: false

addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen

script:
    - make
    - make test
    - make doc

matrix:
  include:
    - compiler: clang
      os: osx
    - compiler: gcc
    - compiler: clang
    - compiler: clang
      sudo: required
      dist: trusty
    - compiler: clang
      env: CMAKE_GENERATOR="-G Ninja"
      dist: trusty

# TODO: Build Ninja
