# "It took the night to believe"

language: c

before_script:
  - cmake $CMAKE_GENERATOR .
  
sudo: required

env:
  - CTEST_OUTPUT_ON_FAILURE=1

addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen
    - ninja-build

script:
    - make
    - make test
    - make doc

matrix:
  include:
    - compiler: clang
      os: osx
      before_install:
        - brew update
        - brew install popt
    - dist: precise
      sudo: false
    - compiler: clang
      dist: trusty
    - compiler: clang
      env: CMAKE_GENERATOR="-G Ninja"
      dist: trusty

# TODO: Build Ninja
